= Curriculum Vitae
Felipe Ribeiro <iamfeliperibeiro@gmail.com>
v1.2, Mar 27th, 2019
:toc2:
:toclevels: 2
:icons: font
:linkattrs:
:sectlink:
:source-language: asciidoc

// Refs
:link-tvglobo: http://redeglobo.globo.com
:link-globoplay: https://globoplay.globo.com
:link-orga: http://optiva.com
:link-tim: http://www.tim.com.br/sp/para-voce
:link-chevron: https://www.chevron.com.br
:link-gmaps: https://goo.gl/maps/gArE2LeZ6xS2
:link-delphos: http://www.delphos.com.br
:link-tjrj: http://www.tjrj.jus.br
:link-stefanini: https://stefanini.com/pt/about/
:link-resume: https://github.com/gohackfelipe/feliperibeiro-resume

== Personal Details
[horizontal]
Name:: Felipe Ribeiro Santos
E-mail:: emaildofeliperibeiro@gmail.com
Academic E-mail:: felipe.santos@uniriotec.br
Phone:: +5521988989293
Date of Birthday:: 08/24/1988
WebSite / Social Media::
* icon:twitter[] https://twitter.com/gohackfelipe[Twitter, role="external", window="_blank"] 
* icon:github[] https://github.com/gohackfelipe[GitHub, role="external", window="_blank"]
* icon:linkedin[] https://linkedin.com/in/1feliperibeiro[LinkedIn, role="external", window="_blank"]
* icon:facebook[] https://www.facebook.com/eufeliperibeiro[Facebook, role="external", window="_blank"]
* icon:link[] http://lattes.cnpq.br/2759531476289413[Lattes (CNPQ), role="external", window="_blank"]
Location:: {link-gmaps}[Duque de Caxias, Rio de Janeiro - Brazil]

[cols="^", options="header"]
|===
| Software geek, tech guy, drum player, likes to +
  travel, meet new people, share knowledge, +
  watch movies/series. +
  +
  Hands on Software/Cloud/Platform & DevOps Engineer. +
  +
  Believer in people, teams, lifelong learning and +
  enjoying life!
  +
  +
  This resume was generated by code.
  +
  Dont you belive?
  +
  Just check {link-resume}[here, role="external", window="_blank"]
|===

<<<
== Professional experience

=== Leader of Devsecops Engineers at TV Globo
icon:calendar[title="Period"] `Jun 2017 to Now (ongoing)` +
icon:group[title="Employer"] {link-tvglobo}[TV Globo, role="external", window="_blank"] +

--
[horizontal]
Position:: *Leader of Cloud/Platform & DevOps Engineer* +
Responsible for the design and implementation of the Cloud Platform Architecture and ensuring that implemented 
services are used for multiple product propositions
--
* *Competence Lead*
    ** Set-up the internal development team
    ** Responsible for the professional/people development for a group of software/devops engineers
    ** Create agile awareness and implement SCRUM development methodology
    ** To organize workshops and dojo`s experiencing for new devops tools ways.
* *Lead of devsecops team* responsible to share the knowledge about tools and devops culture around the company and setup a team responsible for availability, latency,
performance, efficiency, change management, emergency response and planning of capacity.
* *Drive the implementation of the Cloud infrastructure* and services using Agile/Scrum/SAFe approach
* *Definition of strategy to migrate to cloud*
* *System Optimization* for miniable costs on Cloud Infrastructure
* Organized various workshops to *create awareness on Cloud architectures and development approach*
* Implementation of a *Continuous Integration & Deployment environment*
    ** Docker images are build using a Jenkins cluster and pushed to Amazon ECR Docker repositories (Stash -> Jenkins -> AWS ECR) using Jenkins Pipelines
* *Infrastructure as Code*
    ** Creation of *Terraform* modules to enable *Continuous Deployment of the infrastructure and services*
* Implemented *Microservice architecture*
    ** Deployment based on *Docker* Images using *AWS ECS Container Services*
    ** Service interfaces are based on *REST and/or Amazon SQS/RabbitMQ AMQP* broker
    ** __"Service Discovery"__ based on *Consul*
    ** __"Trace of Services"__ using *Zipkin*
    ** Service implementations using Python, Node.js
    ** Infrastructure and service monitoring using *CloudWatch/Prometheus*


*Technologies used:* +
Docker, Java, Node.js, Python, Javascript, Angular, Consul, Terraform, AWS Webservices, (EC2, ECS, ECR, ELB, S3, CloudWatch, Elasticsearch, RDS,
CloudFront, Cognito, Certificate Manager, Elastic Beanstalk), RabbitMQ, SQS,
REST, Tomcat, Linux, Neo4J, Mysql, MongoDB, Oracle, Git, Confluence, 
Scrum, SAFe (Scaled Agile Framework), Prometheus, Microservices, Terraform, Packer, Jenkins, Zipkin

'''

=== Technical Lead/Software Engineer/Architect at TV Globo
icon:calendar[title="Period"] `Jun 2015 to Jun 2017` +
icon:group[title="Employer"] {link-tvglobo}[TV Globo, role="external", window="_blank"] +

--
[horizontal]
Position:: *Technical Lead/Software Engineer/Architect* +
Responsible for design & implementation of a web-based platform to TV Live shows and corporative solutions. 
--

* *Competence Lead*
    ** Responsible for the technical development for a group of software engineers
    ** Implementation of distributed development environment and process (requirements, development, testing & deployment)
    ** Gathering functional & non-functional requirement
    ** Create agile awareness and implement SCRUM development methodology
* *Innovation Architect*
    ** Being part of the "Agile Development team" creating innovative concepts, technologies & methodologies. Responsible for the architecture, selection, progress and staffing
* *Software Engineer*
    ** Collaborated with various *stakeholders, clients and internal areas* to develop solutions to aim our telespector
    ** Implementation of different mobile applications, infrastructures and technologies
    ** To build web architectures solutions able to organic capacity expecting 1 million of requests / hour.
    ** Responsible for the design, development and the implementation of a number of applications. Applications have been developed using Node.js
    ** Trainer for Cloud and Devops course at TV Globo Tech Academy. Introducing concepts such as devops culture, new approachs,tools and design directives
    ** *Implementing* the design together with a team

*Methodologies & Technologies used:* +
Java, Python, Node.js, Javascript, REST, GraphQL, JMeter, SoapUI, XML, SOAP, JSON, RabbitMQ, Linux, MySQL, PostgreSQL, MongoDB, Agile,
AWS Webservices (EC2, ECS, ECR, ELB, S3, CloudWatch, Elasticsearch, RDS, CloudFront, Cognito, Certificate Manager), Git,
Android Studio, Xcode

'''

=== Software Engineer at Orga Systems (Acquired by Redknee)
icon:calendar[title="Period"] `Jul 2014 to Set 2015` +
icon:group[title="Employer"] {link-orga}[Orga Systems (Acquired by Redknee), role="external", window="_blank"] +
icon:chevron-circle-right[title="Customer"] {link-tim}[Tim Brazil Company, role="external", window="_blank"]

--
[horizontal]
Position:: *Software engineer at Orga Systems* +
Development a Java/Web based Billing system for communication companys at Brazil
--

* Implementation of distributed *development* environment and process (requirements, development, testing & deployment)
* Development of *high traffic* based website for http://www.tim.com.br[Tim Brazil Company]
* Implementation of different *mobile applications, infrastructures and technologies*

*Methodologies & Technologies used:* +
Java, JEE, Spring, Struts, JSF, Hibernate, Javascript, ExtJS, JQuery JBoss, JUnit, JMeter, UML, Jenkins, Python, Javascript, Android Studio, Oracle Database

'''

=== Software Engineer at Stefanini IT Solutions
icon:calendar[title="Period"] `Jul 2010 to Jul 2014` +
icon:group[title="Employer"] {link-stefanini}[Stefanini, role="external", window="_blank"] +
icon:chevron-circle-right[title="Customer"] {link-tjrj}[Rio de Janeiro Courtey of Justice, role="external", window="_blank"]

--
[horizontal]
Position:: *Software Engineer*
--
* Responsible for the design, development and the implementation of a number of applications.
* Development of high traffic based website for http://www.tjrj.jus.br [Rio de Janeiro Courtey of Justice]
* Development of Web Applications for Judiciary Public 

*Methodologies & Technologies used:* +
Java, Eclipse, NetBeans, Java J2SE, Oracle, Web Services, UML, JUnit, Tomcat, J2EE, PostgreSQL, Oracle Database, J2ME, OC4j, Struts, JSF,Sencha (ExtJS), SVN

'''

=== Programmer at Delphos
icon:calendar[title="Period"] `Jan 2009 to Jun 2010` +
icon:group[title="Employer"] {link-delphos}[Delphos, role="external", window="_blank"] +

--
[horizontal]
Position:: *Programmer* +
Programmer responsible for development of insurancy projects
--

* Responsible for the design, development and the implementation of a number of applications.
* Development of solutions for Insurancy companys using Oracle technologies as Oracle Forms, Oracle Design and Oracle Reports.

*Methodologies & Technologies used:* +
Java, Eclipse, NetBeans, Java J2SE, Oracle Database, Web Services, UML, JUnit, Tomcat, Glassfish, J2EE, Oracle Database, Struts, JSF, SVN

'''

=== Developer Intern at Chevron Brazil Petróleo
icon:calendar[title="Period"] `Mar 2008 to Mar 2009` +
icon:group[title="Employer"] {link-chevron}[Chevron Brasil, role="external", window="_blank"] +

--
[horizontal]
Position:: *Developer Intern* +
Developer Intern for Lubrificants Factory (Texaco)
--

* Responsible for the design, development and the implementation of a number of applications. Applications have been developed using Java.
* Development of solutions for Lubrificants Factory (Texaco) using Oracle technologies as Oracle Forms, Oracle Design and Oracle Reports.

*Methodologies & Technologies used:* +
Java, Eclipse, NetBeans, Java J2SE, Oracle Database, Web Services, UML, JUnit, SVN

<<<
== Technical Skills

Containers:: Docker, Docker Compose, Docker Swarm, AWS ECS

Webservices:: SOAP, REST, JSON, SoapUI, Postman, Microservices

Cloud:: AWS, AWS EC2, AWS ECS, AWS ELB/ALB, AWS ElasticSearch, AWS Lambda, AWS Kibana, AWS SQS, AWS Cognito, Terraform, CloudFormation, Prometheus, Consul

Languages and Specifications:: Java, Node.js, Python, Go, Elixir, JavaScript, AsciiDoc, HTML5, Markdown, Shell scripting, XML, CSS

Software Engineering:: DevOps, ChatOps, Continuous Integration, Continuous Delivery, Unit Testing, Integration Testing

Frameworks and Libraries:: Express.js, Flask, Django, Passport, Lodash, Yarn and much more.. :)

Databases:: MySQL, Oracle, AWS DynamoDB, MongoDB, PostgreSQL

OS:: Linux, Mac OSX, Windows

Protocols:: HTTP, WebSockets, REST, JMS

Tools:: IntelliJ, Eclipse, JIRA, Git, Jenkins, Sonar, Nexus, JMeter

Methodologies:: TDD, Agile/Scrum, SAFe (Scaled Agile Framework)


<<<
== Education

[cols="90%,>10%", options="header"]
|===
| Name                                                  | Year
| *Graduate* - Rio de Janeiro State University (UERJ), Computer Science | 2010
| *Master* - Rio de Janeiro Federal University (UNIRIO), *Research*: Agile Development | 2020
| Visual Studio DevOps: Visual Studio and Azure         | 2017
| AWS Certified Developer - Associate 2018              | ongoing
| AWS Certified SysOps Administrator - Associate 2018   | ongoing
| AWS Certified Solutions Architect                     | ongoing
| AWS Certified DevOps Engineer - Professional          | ongoing
|===

== Interests

* *Learning:* Always interested in learning new technologies & methodologies, currently looking at: Serverless Computing, Google Cloud/Kubernetes, Elixir, Golang and ChatOps
* *Travelling:* Like to experience new cultures, environments and meeting new people
* *Playing*: Drums..